feat: добавить функциональность вещей и пользователей
bad-decision/java-shareit pull request #1
Opened 2022-10-21 20:57 UTC by bad-decision

2022-10-22 19:45 UTC, bad-decision commented
Сорян, забыл сделать публичным.

2022-10-23 19:48 UTC, sergeymamonov requested changes

2022-10-23 19:48 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/common/handler/ErrorHandlingControllerAdvice.java
> +
А если возникнет рантайм ошибка? Хорошо бы ее тоже обработать.

2022-10-23 19:48 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    @Mapping(target = "available", source = "available")
Использование Mapstruct это отлично. Зачем явно указывать target = "available", source = "available"? У этого поля одинаковое название и тип в классах. Не вижу необходимости писать явно. То есть удалив эту строку, будет работать и без нее.

2022-10-24 06:59 UTC, bad-decision commented on src/main/java/ru/practicum/shareit/common/handler/ErrorHandlingControllerAdvice.java
> +
Добавил

2022-10-25 03:37 UTC, sergeymamonov approved these changes

2022-10-25 04:59 UTC, merged