Add item requests
bad-decision/java-shareit pull request #3
Opened 2022-11-22 21:02 UTC by bad-decision

2022-11-24 20:36 UTC, sergeymamonov requested changes

2022-11-24 20:36 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>          for (Item item : items) {
Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД. Как в данной ситуации можно уйти от цикла:
1. Выгружаем комментарии, группируем их по вещам и конвертируем в dto
2. Выгружаем подтвержденные бронирования отсортированные по дате начала и группируем их по вещам
3. Для каждой вещи находим последнее и следующее бронирование, а также комментарии и формируем результат

2022-11-24 20:36 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +        owner.setEmail("test@mail.ru");
Для общего развития посмотрите в ломбоке билдер, с ним получается меньше текста при создании объектов.

2022-11-24 20:36 UTC, sergeymamonov commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    private final EntityManager em;
Странно выглядит, выше названия бинов написаны полностью, а здесь двумя буквами.

2022-11-26 19:51 UTC, bad-decision commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        if (from < 0 || size <= 0) {
Поправил

2022-11-26 19:51 UTC, bad-decision commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>          for (Item item : items) {
Поправил.

2022-11-26 19:52 UTC, bad-decision commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +        owner.setEmail("test@mail.ru");
Не стал весь проект под одну аннотацию переделывать, но добавил в один класс эту аннотацию.

2022-11-26 19:52 UTC, bad-decision commented on src/test/java/ru/practicum/shareit/booking/service/BookingServiceImplTest.java
> +    private final EntityManager em;
Поправил.

2022-11-27 21:08 UTC, sergeymamonov approved these changes

2022-11-28 08:43 UTC, merged