Add docker
bad-decision/java-shareit pull request #4
Opened 2022-11-30 18:04 UTC by bad-decision

2022-12-01 20:38 UTC, sergeymamonov requested changes

2022-12-01 20:38 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
На строке 65 лучше добавить ветку default. И проверить все остальные свитчи.

2022-12-01 20:38 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>          Pageable pageable = PageRequest.of(from / size, size, Sort.by("start").descending());
Не нашел валидацию, что size должен быть больше 0. Если пользователь передаст 0, здесь будет деление на ноль. size и from должны быть провалидированы. Лучше это сделать в сервисе gateway.

2022-12-03 17:18 UTC, bad-decision commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
Поправил.

2022-12-03 17:18 UTC, bad-decision commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>          Pageable pageable = PageRequest.of(from / size, size, Sort.by("start").descending());
Поле size валидируется через аннотацию контроллера gateway.  На это есть и собственные тесты и тесты postman, которые запускаются при merge request.

2022-12-03 20:11 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>          Pageable pageable = PageRequest.of(from / size, size, Sort.by("start").descending());
Да, замечание некорректное. Все верно.

2022-12-03 20:12 UTC, sergeymamonov approved these changes

2022-12-03 20:14 UTC, merged